Story 2
iO-Academy/2024-mar-sde-furniture-store-panda-monium pull request #1
Opened 2024-05-20 13:58 UTC by CJD115

https://trello.com/c/lpla9cso/35-story-2-list-product-categories

2024-05-20 14:17 UTC, ashleycoles requested changes
Great start, a few changes to keep you all busy :)

2024-05-20 14:17 UTC, ashleycoles commented on src/Factory/Factory.php
> +class Factory
You should rename this, Factory is way to generic. Make sure you rename the class and the file please

2024-05-20 14:17 UTC, ashleycoles commented on src/Models/CategoryModel.php
> +
Why all this space?

2024-05-20 14:17 UTC, ashleycoles commented on src/Models/CategoryModel.php
> +    public static function getCategories(PDO $db)
Return type hint

2024-05-20 14:17 UTC, ashleycoles commented on src/Models/CategoryModel.php
> +
Whitespace remove plz

2024-05-20 14:17 UTC, ashleycoles commented on src/Entities/CategoryEntity.php
> +    }
This method needs to be unit tested, however because your entity is created using `PDO::FETCH_CLASS`, you cannot instantiate this entity in order to test it.

What you should do instead is create a new class (like a category display service) that has the displayCategory method which accepts a CategoryEntity as an argument. This method could be static like your factory connect method.

That then makes this display code unit testable, and better follows the single responsibility principle as the entity strictly contains the data and doesn't do anything else.

2024-05-20 14:17 UTC, ashleycoles commented on src/Entities/CategoryEntity.php
> +
Only one line of whitespace above plz

2024-05-20 14:17 UTC, ashleycoles commented on index.php
> +
1 line of whitespace

2024-05-20 14:17 UTC, ashleycoles commented on index.php
> +
1 line of whitespace

2024-05-20 14:17 UTC, ashleycoles commented on index.php
> +require_once 'src/Entities/CategoryEntity.php';
Do you need all these require statements to be here?

2024-05-20 14:17 UTC, ashleycoles commented on src/Entities/CategoryEntity.php
> +    }
Make sure to return type hint this when you do it as well :)

2024-05-21 10:04 UTC, mporam requested changes

2024-05-21 10:04 UTC, mporam commented on UnitTests/TestCategoryDisplayService.php
> +
missing malformed test

2024-05-21 10:04 UTC, mporam commented on src/Entities/CategoryEntity.php
> +    public function getName()
missing return type

2024-05-21 10:04 UTC, mporam commented on src/Entities/CategoryEntity.php
> +    public function getStockTotal()
missing return type

2024-05-21 12:59 UTC, mporam approved these changes

2024-05-21 12:59 UTC, merged